export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const BOOKS_FETCHED = "BOOKS_FETCHED";
export const BOOK_CREATED = "BOOK_CREATED";

export const LIST_REMOVED = "LIST_REMOVED";
export const LIST_ADDED = "LIST_ADDED";
export const LIST_EDITTED = "LIST_EDITTED";

export const CARD_MOVED = "CARD_MOVED";
export const CARD_ADDED = "CARD_ADDED";
export const CARD_REMOVED = "CARD_REMOVED";
export const CARD_MOVED_ON_LIST = "CARD_MOVED_ON_LIST";
export const ADDED_COMMENT_TO_CARD = "ADDED_COMMENT_TO_CARD";
export const REMOVED_COMMENT_FROM_CARD = "REMOVED_COMMENT_FROM_CARD";
export const EDITTED_COMMENT = "EDITTED_COMMENT";
export const EDITTED_CARD_NAME = "EDITTED_CARD_NAME";
export const LIST_MOVED = "LIST_MOVED";
export const CARD_DESCRIPTION_EDITTED = "CARD_DESCRIPTION_EDITTED";
export const CARD_MARKED = "CARD_MARKED";
export const CARDS_REMOVED = "CARDS_REMOVED";
export const CARD_COPIED = "CARD_COPIED";
export const CARD_RESTORED = "CARD_RESTORED";

export const BOARD_ADDED = "BOARD_ADDED";
